# Generated by Django 3.2.8 on 2021-10-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Auth User', 'verbose_name_plural': 'Auth Users'},
        ),
        migrations.AlterUniqueTogether(
            name='userbase',
            unique_together={('username', 'phone')},
        ),
    ]
