# Generated by Django 3.2.8 on 2021-10-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20211026_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
