# Generated by Django 3.2.8 on 2021-10-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_userbase_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='username',
            new_name='full_name',
        ),
        migrations.AlterUniqueTogether(
            name='userbase',
            unique_together={('full_name', 'phone')},
        ),
    ]
