# Generated by Django 3.2.8 on 2021-10-26 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_auto_20211026_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Auth User', 'verbose_name_plural': 'Auth Users'},
        ),
        migrations.AddField(
            model_name='userbase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
