# Generated by Django 3.2.8 on 2021-10-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_auto_20211026_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='userbase',
            unique_together=set(),
        ),
    ]
