# Generated by Django 3.2.8 on 2021-10-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20211026_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
