# Generated by Django 3.2.8 on 2021-10-26 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_userbase_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
